const config = require('./config.json')
const csv = require('csv-parser')
const fs = require('fs')

/**
  * @desc Process each CSV row and try to find a new machine.
  * @param  string $machines - the machines array
  * @param  string $row - CSV row generated by csv-parser
  * @returns null
*/
const FindMachine = function (machines, row) {
  const machineName = row[config.fileds.machine]
  if (machineName !== config.fileds.machine) {
    const machineIndex = machines.findIndex((element) => element == machineName)
    if (machineIndex === -1) {
      machines.push(machineName)
    }
  }
}

const GetMachineList = function (req, res) {
  const machines = []
  // Open the file
  fs.createReadStream(config.dataFile)
    .pipe(csv(config.dataHeaders))
    .on('data', (row) => {
      // Process each row
      FindMachine(machines, row)
    })
    .on('end', () => {
      // Send the response after process all the file.
      res.send(machines)
    })
}

module.exports = GetMachineList
